sonar.projectKey=nextjs-myapp
sonar.organization=myorg
sonar.sources=.
sonar.exclusions=**/mfes/content/public/content/**,ai-gateway/**,apps/teachers/src/services/**,apps/learner-web-app/src/components/SignupSuccess/**
sonar.coverage.exclusions=ai-gateway/**,apps/teachers/src/services/**,apps/learner-web-app/src/components/SignupSuccess/**
sonar.cpd.exclusions=ai-gateway/**,apps/teachers/src/services/**,apps/learner-web-app/src/components/SignupSuccess/**
