"""
AI Engine — Module A: Intelligent Document Ingestion
=====================================================
Implements the full Module-A pipeline described in DMP_2026.yml:

  1. PDF parsing  → structured JSON (headers, body_text, images, metadata)
  2. Key Takeaways → extractive summarisation from source text (sentence
                     scoring via TF-IDF cosine similarity). No hallucination.
  3. Glossary      → domain-term extraction strictly from source text using
                     noun-phrase frequency heuristics + spaCy (if available).
  4. Narration Script → If GROQ_API_KEY is set, generated by Llama 3-8b-8192
                        via Groq Cloud, strictly grounded in the source text.
                        Falls back to a clean extractive script when the key
                        is absent or the call fails.

Design constraints
------------------
* All primary work is done locally (PyMuPDF + scikit-learn + sentence-
  transformers). No external network calls are mandatory.
* The Groq path is an *optional enhancement* — the endpoint always succeeds
  even without a GROQ_API_KEY.
* Text fed to any LLM is always the actual extracted body text, never a
  hallucinated source. System prompts forbid fabrication.
"""

from __future__ import annotations

import base64
import logging
import math
import os
import re
import tempfile
from collections import Counter
from typing import Annotated

import fitz  # PyMuPDF
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware

# Load .env from the service directory (git-ignored, never committed)
load_dotenv()

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
MAX_FILE_SIZE = 10 * 1024 * 1024   # 10 MB
_CHUNK_SIZE   = 64 * 1024          # 64 KB per read

# Groq / LLM settings
GROQ_API_KEY       = os.environ.get("GROQ_API_KEY", "")
GROQ_MODEL         = os.environ.get("GROQ_MODEL", "llama3-8b-8192")
LLM_MAX_TOKENS     = 1024
# Max chars sent to LLM (keep prompt within context window)
LLM_CONTEXT_CHARS  = 6000

# Extraction limits
MAX_TAKEAWAYS      = 7
MAX_GLOSSARY_TERMS = 15

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------
app = FastAPI(
    title="AI Engine API — Module A",
    description=(
        "Intelligent Document Ingestion pipeline: PDF parsing, "
        "key-takeaway extraction, glossary generation, and narration scripting."
    ),
    version="1.1.0",
)

_DEV_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_DEV_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["Content-Type", "Accept"],
)

# ---------------------------------------------------------------------------
# Optional heavy imports — degrade gracefully if not available
# ---------------------------------------------------------------------------
try:
    import spacy
    _nlp = spacy.load("en_core_web_sm")
    _SPACY_OK = True
    logger.info("spaCy en_core_web_sm loaded — noun-phrase glossary active.")
except Exception:
    _nlp = None
    _SPACY_OK = False
    logger.info("spaCy not available — using regex noun-phrase fallback.")

try:
    from groq import Groq as GroqClient
    _GROQ_SDK_OK = True
except ImportError:
    _GROQ_SDK_OK = False

# ---------------------------------------------------------------------------
# Helpers — upload / streaming
# ---------------------------------------------------------------------------

async def _read_bounded_to_disk(file: UploadFile, max_bytes: int) -> str:
    """Stream upload in chunks to a temp file; raise 413 if limit exceeded."""
    total = 0
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    try:
        with tmp:
            while True:
                chunk = await file.read(_CHUNK_SIZE)
                if not chunk:
                    break
                total += len(chunk)
                if total > max_bytes:
                    raise HTTPException(
                        status_code=413,
                        detail="File too large. Maximum allowed size is 10 MB.",
                    )
                tmp.write(chunk)
        return tmp.name
    except Exception:
        if os.path.exists(tmp.name):
            os.unlink(tmp.name)
        raise


# ---------------------------------------------------------------------------
# Module A — Step 2: Extractive Key Takeaways
# ---------------------------------------------------------------------------

def _split_sentences(text: str) -> list[str]:
    """Minimal sentence splitter — no NLTK dependency."""
    raw = re.split(r"(?<=[.!?])\s+", text)
    return [s.strip() for s in raw if len(s.strip()) > 40]


def _tfidf_score(sentences: list[str]) -> list[tuple[float, str]]:
    """
    Score sentences by average TF-IDF weight of their tokens.
    Grounded entirely in the document's own vocabulary.
    """
    if not sentences:
        return []

    # Build vocabulary
    stop_words = {
        "the","a","an","and","or","but","in","on","at","to","for","of",
        "with","is","are","was","were","be","been","being","have","has",
        "had","do","does","did","will","would","could","should","may",
        "might","shall","can","not","this","that","these","those","it",
        "its","by","as","from","if","then","than","so","into","about",
        "also","which","who","what","when","where","how","all","each",
        "both","more","most","other","such","only","just","any","there",
    }

    def tokenize(s: str) -> list[str]:
        return [
            w.lower() for w in re.findall(r"\b[a-zA-Z]{3,}\b", s)
            if w.lower() not in stop_words
        ]

    n = len(sentences)
    # TF per sentence
    tf_list = [Counter(tokenize(s)) for s in sentences]
    # DF across all sentences
    df: Counter = Counter()
    for tf in tf_list:
        df.update(tf.keys())

    scored: list[tuple[float, str]] = []
    for idx, (tf, sent) in enumerate(zip(tf_list, sentences)):
        if not tf:
            scored.append((0.0, sent))
            continue
        score = sum(
            count * math.log((n + 1) / (df[word] + 1))
            for word, count in tf.items()
        )
        # Small positional bonus for earlier sentences (intro/abstract)
        position_bonus = 1.0 + max(0.0, 0.3 * (1 - idx / n))
        scored.append((score * position_bonus, sent))

    return scored


def extract_key_takeaways(body_text: str, n: int = MAX_TAKEAWAYS) -> list[str]:
    """
    Return up to `n` key sentences extracted *directly* from `body_text`.
    No external model or network call — fully deterministic, no hallucination.
    """
    sentences = _split_sentences(body_text)
    if not sentences:
        return []

    scored = _tfidf_score(sentences)
    scored.sort(key=lambda x: x[0], reverse=True)
    top = [s for _, s in scored[:n]]

    # Re-order by original position for readability
    order = {sent: i for i, sent in enumerate(sentences)}
    top.sort(key=lambda s: order.get(s, 0))
    return top


# ---------------------------------------------------------------------------
# Module A — Step 3: Glossary Extraction
# ---------------------------------------------------------------------------

def _extract_noun_phrases_spacy(text: str) -> list[str]:
    doc = _nlp(text[:100_000])  # spaCy limit guard
    phrases = []
    for chunk in doc.noun_chunks:
        phrase = chunk.text.strip().lower()
        # Keep multi-word or capitalised single-word phrases (likely terms)
        if len(phrase.split()) > 1 or chunk.text[0].isupper():
            phrases.append(phrase)
    return phrases


def _extract_noun_phrases_regex(text: str) -> list[str]:
    """
    Fallback: extract capitalised multi-word sequences as candidate terms.
    E.g. "Transformer Architecture", "Retrieval-Augmented Generation"
    """
    pattern = re.compile(r"\b([A-Z][a-z]+(?:[\s\-][A-Z][a-z]+)+)\b")
    return [m.group(0).lower() for m in pattern.finditer(text)]


def _build_definition(term: str, sentences: list[str]) -> str:
    """
    Find the sentence that best contextualises the term and return a
    truncated, cleaned version as the definition.
    """
    term_lower = term.lower()
    # Prefer sentences that contain the term
    candidates = [
        s for s in sentences
        if term_lower in s.lower() and len(s) > 50
    ]
    if not candidates:
        return ""
    # Shortest match is usually the most focused definition sentence
    best = min(candidates, key=len)
    # Trim to ~120 chars for readability
    return best[:180].rstrip(",;") + ("…" if len(best) > 180 else "")


def extract_glossary(
    body_text: str,
    n: int = MAX_GLOSSARY_TERMS,
) -> dict[str, str]:
    """
    Build a glossary of domain terms extracted *from the document itself*.
    Definitions are sentences taken verbatim from the source text.
    No hallucination possible — every definition is a document substring.
    """
    sentences = _split_sentences(body_text)
    if not sentences:
        return {}

    if _SPACY_OK:
        phrases = _extract_noun_phrases_spacy(body_text)
    else:
        phrases = _extract_noun_phrases_regex(body_text)

    if not phrases:
        return {}

    # Count frequency, keep most frequent unique terms
    freq = Counter(p.strip() for p in phrases if 2 <= len(p) <= 60)
    top_terms = [term for term, _ in freq.most_common(n * 3)]

    glossary: dict[str, str] = {}
    for term in top_terms:
        if len(glossary) >= n:
            break
        defn = _build_definition(term, sentences)
        if defn:
            # Title-case the term for display
            display_term = term.title()
            glossary[display_term] = defn

    return glossary


# ---------------------------------------------------------------------------
# Module A — Step 4: Narration Script
# ---------------------------------------------------------------------------

_NARRATION_SYSTEM_PROMPT = """\
You are an educational narration writer for an e-learning platform.
Your ONLY job is to write a professional narration script for a slide-deck
or lesson based on the document text provided by the user.

STRICT RULES — you must follow these without exception:
1. Use ONLY the information present in the provided document text.
2. Do NOT invent facts, statistics, names, or concepts not in the text.
3. Do NOT add personal opinions, external knowledge, or assumptions.
4. Write in a clear, friendly, second-person teacher voice ("In this section…").
5. Structure: short intro → main points (drawn from document) → brief close.
6. Output plain text only — no markdown, no bullet points, no headers.
7. Keep the script under 300 words.
"""


def _build_narration_extractive(
    key_takeaways: list[str],
    headers: list[str],
) -> str:
    """
    Pure-extractive fallback narration script — no LLM, no hallucination.
    Constructed entirely from document sentences already extracted.
    """
    lines: list[str] = []

    if headers:
        topic = headers[0]
        lines.append(f"Welcome. In this lesson we will explore: {topic}.")
    else:
        lines.append("Welcome to this lesson.")

    if key_takeaways:
        lines.append("Here are the key points from this document:")
        for i, point in enumerate(key_takeaways[:5], 1):
            lines.append(f"{i}. {point}")

    lines.append(
        "That concludes the core content. "
        "Review the glossary for definitions of key terms."
    )
    return " ".join(lines)


def generate_narration_script(
    body_text: str,
    key_takeaways: list[str],
    headers: list[str],
) -> str:
    """
    Generate a narration script.
    * If GROQ_API_KEY is set: call Llama 3 via Groq Cloud with strict
      grounding system prompt and the real document text as context.
    * Otherwise: fall back to extractive script (no hallucination).
    """
    # Extractive fallback always works
    fallback = _build_narration_extractive(key_takeaways, headers)

    if not GROQ_API_KEY or not _GROQ_SDK_OK:
        logger.info("Narration: using extractive fallback (no GROQ_API_KEY).")
        return fallback

    # Trim body text to context window
    context_text = body_text[:LLM_CONTEXT_CHARS]
    user_message = (
        "Write a narration script for the following document.\n\n"
        f"--- DOCUMENT TEXT START ---\n{context_text}\n--- DOCUMENT TEXT END ---"
    )

    try:
        client = GroqClient(api_key=GROQ_API_KEY)
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _NARRATION_SYSTEM_PROMPT},
                {"role": "user",   "content": user_message},
            ],
            max_tokens=LLM_MAX_TOKENS,
            temperature=0.3,   # Low temperature → more faithful to source
        )
        script = response.choices[0].message.content.strip()
        logger.info("Narration: Groq LLM script generated (%d chars).", len(script))
        return script
    except Exception as exc:
        logger.warning("Narration: Groq call failed (%s) — using extractive fallback.", exc)
        return fallback


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health")
def health_check() -> dict:
    """Liveness probe — returns service capabilities."""
    return {
        "status": "healthy",
        "llm_backend": "groq" if (GROQ_API_KEY and _GROQ_SDK_OK) else "extractive",
        "groq_model": GROQ_MODEL if (GROQ_API_KEY and _GROQ_SDK_OK) else None,
        "spacy_available": _SPACY_OK,
    }


@app.post("/ingest")
async def ingest_pdf(file: Annotated[UploadFile, File(...)]) -> dict:
    """
    Module A — Full ingestion pipeline.

    1. Validate & stream PDF to disk.
    2. Extract structure via PyMuPDF (headers, body_text, images, metadata).
    3. Extract Key Takeaways (TF-IDF extractive — grounded in source text).
    4. Extract Glossary (noun-phrase frequency — grounded in source text).
    5. Generate Narration Script (extractive or Groq Llama 3 — grounded).

    Returns structured JSON matching the IngestResponse TypeScript interface.
    """
    # ── Validate content-type ──────────────────────────────────────────────
    content_type = (file.content_type or "").split(";")[0].strip().lower()
    if content_type != "application/pdf":
        raise HTTPException(
            status_code=400,
            detail="Unsupported file type. Only PDF files are accepted.",
        )

    temp_path: str | None = None

    try:
        # ── Step 1: Stream to disk ─────────────────────────────────────────
        temp_path = await _read_bounded_to_disk(file, MAX_FILE_SIZE)

        if os.path.getsize(temp_path) == 0:
            raise HTTPException(status_code=400, detail="Empty file uploaded.")

        # ── Step 2: Parse PDF structure ────────────────────────────────────
        with fitz.open(temp_path) as doc:
            if doc.page_count == 0:
                raise HTTPException(status_code=400, detail="PDF has no pages.")

            metadata  = doc.metadata or {}
            headers:         list[str]  = []
            body_text_parts: list[str]  = []
            images:          list[dict] = []

            for page_num in range(doc.page_count):
                page   = doc.load_page(page_num)
                blocks = page.get_text("dict").get("blocks", [])

                for b in blocks:
                    if b.get("type") != 0:
                        continue
                    for line in b.get("lines", []):
                        for span in line.get("spans", []):
                            text = span.get("text", "").strip()
                            if not text:
                                continue
                            font_size = span.get("size", 0)
                            is_bold   = bool(span.get("flags", 0) & 2 ** 4)
                            if font_size > 14 or is_bold:
                                if text not in headers:
                                    headers.append(text)
                            body_text_parts.append(text)

                for img_index, img in enumerate(page.get_images(full=True)):
                    xref       = img[0]
                    base_image = doc.extract_image(xref)
                    image_bytes = base_image.get("image")
                    if image_bytes:
                        images.append({
                            "page":  page_num + 1,
                            "index": img_index,
                            "ext":   base_image.get("ext"),
                            "data":  base64.b64encode(image_bytes).decode("utf-8"),
                        })

        body_text = " ".join(body_text_parts)

        if not body_text.strip():
            # Scanned / image-only PDF — return structure without AI layers
            return {
                "headers":          headers,
                "body_text":        body_text,
                "images":           images,
                "metadata":         metadata,
                "key_takeaways":    [],
                "glossary":         {},
                "narration_script": "",
                "pipeline_note":    "No extractable text — PDF may be image-only.",
            }

        # ── Step 3: Key Takeaways (extractive) ────────────────────────────
        logger.info("Extracting key takeaways…")
        key_takeaways = extract_key_takeaways(body_text)

        # ── Step 4: Glossary (extractive) ──────────────────────────────────
        logger.info("Extracting glossary…")
        glossary = extract_glossary(body_text)

        # ── Step 5: Narration Script (LLM or extractive fallback) ──────────
        logger.info("Generating narration script…")
        narration_script = generate_narration_script(
            body_text, key_takeaways, headers
        )

        logger.info(
            "Ingestion complete — takeaways=%d, glossary=%d, script=%d chars.",
            len(key_takeaways), len(glossary), len(narration_script),
        )

        return {
            "headers":          headers,
            "body_text":        body_text,
            "images":           images,
            "metadata":         metadata,
            "key_takeaways":    key_takeaways,
            "glossary":         glossary,
            "narration_script": narration_script,
        }

    except (fitz.FileDataError, fitz.EmptyFileError):
        logger.error("PyMuPDF failed — corrupted or invalid PDF.")
        raise HTTPException(
            status_code=400,
            detail="Failed to parse PDF. Ensure the file is a valid, non-encrypted PDF.",
        )
    finally:
        if temp_path and os.path.exists(temp_path):
            os.unlink(temp_path)
