/**
 * Templates for H5P package generation.
 */

export const H5P_MANIFEST_TEMPLATE = {
  title: "AI Generated Lesson",
  language: "en",
  mainLibrary: "H5P.QuestionSet",
  embedTypes: ["div"],
  preloadedDependencies: [
    { machineName: "H5P.QuestionSet", majorVersion: 1, minorVersion: 20 },
    { machineName: "H5P.MultiChoice", majorVersion: 1, minorVersion: 16 },
    { machineName: "H5P.Blanks", majorVersion: 1, minorVersion: 14 },
    { machineName: "H5P.DragText", majorVersion: 1, minorVersion: 10 },
    { machineName: "FontAwesome", majorVersion: 4, minorVersion: 5 },
    { machineName: "H5P.FontIcons", majorVersion: 1, minorVersion: 0 },
    { machineName: "H5P.Transition", majorVersion: 1, minorVersion: 0 }
  ]
};

export const QUESTION_SET_PARAMS_TEMPLATE = {
  introPage: {
    showIntroPage: true,
    title: "AI Knowledge Check",
    introduction: "<p>Welcome! This quiz was generated by AI from your instructional material.</p>",
    startButtonText: "Start Quiz"
  },
  questions: [],
  progressType: "dots",
  passPercentage: 50,
  disableBackwardsNavigation: false,
  randomQuestions: false,
  endGame: {
    showResultPage: true,
    showSolutionButton: true,
    showRetryButton: true,
    noResultMessage: "You have finished the quiz!",
    message: "Your result:",
    overallFeedback: [
      { from: 0, to: 50, feedback: "Keep practicing!" },
      { from: 51, to: 100, feedback: "Great job!" }
    ]
  },
  texts: {
    prevButton: "Previous",
    nextButton: "Next",
    finishButton: "Finish",
    submitButton: "Submit"
  }
};
