from textwrap import dedent

from fastapi import FastAPI

from common.models import LessonBuildRequest, LessonBuildResponse
from common.packages import build_lesson_packages

app = FastAPI(title="Lesson Builder Service", version="1.0.0")


@app.get("/health")
async def health() -> dict:
    return {"status": "ok", "service": "lesson-builder"}


@app.post("/build", response_model=LessonBuildResponse)
async def build_lesson(payload: LessonBuildRequest) -> LessonBuildResponse:
    sections_markup = "".join(
        f"<section><h2>{section.heading}</h2><p>{section.body.replace(chr(10), '<br/>')}</p></section>"
        for section in payload.structured_sections
    )
    takeaway_markup = "".join(f"<li>{item}</li>" for item in payload.key_takeaways)
    glossary_markup = "".join(f"<dt>{item.term}</dt><dd>{item.definition}</dd>" for item in payload.glossary)
    chapter_markup = "".join(
        f"<li>{chapter.title} at {chapter.start_seconds}s: {chapter.summary}</li>" for chapter in payload.chapters
    )
    review_panel = (
        "<div class='review approved'>Approved for publishing</div>"
        if payload.approved
        else f"<div class='review pending'>Pending human review: {payload.review_notes or 'Review required before publishing.'}</div>"
    )
    preview_html = dedent(
        f"""\
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>{payload.title}</title>
            <style>
              :root {{
                --primary: {payload.branding.primary_color};
                --secondary: {payload.branding.secondary_color};
                --font: {payload.branding.font_family};
              }}
              body {{
                margin: 0;
                font-family: var(--font), sans-serif;
                color: #10233f;
                background: linear-gradient(135deg, #f7f2e8 0%, #ffffff 45%, #edf4ff 100%);
              }}
              header {{
                padding: 32px;
                background: var(--primary);
                color: white;
              }}
              main {{
                padding: 24px;
                display: grid;
                gap: 20px;
                grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
              }}
              section, article {{
                background: white;
                border-radius: 18px;
                padding: 20px;
                box-shadow: 0 12px 32px rgba(16, 35, 63, 0.08);
              }}
              .hero {{
                grid-column: 1 / -1;
                border-left: 8px solid var(--secondary);
              }}
              .review {{
                margin-top: 12px;
                padding: 10px 14px;
                border-radius: 999px;
                display: inline-block;
                font-weight: 700;
              }}
              .approved {{ background: #d7f5e8; color: #166534; }}
              .pending {{ background: #fff4cc; color: #92400e; }}
              dl {{ display: grid; grid-template-columns: max-content 1fr; gap: 8px 12px; }}
              dt {{ font-weight: 700; color: var(--primary); }}
              footer {{
                padding: 24px;
                text-align: center;
                color: #41526b;
              }}
            </style>
          </head>
          <body>
            <header>
              <div>{payload.branding.logo_text}</div>
              <h1>{payload.title}</h1>
              <p>{payload.branding.name} branded AI micro-learning experience</p>
              {review_panel}
            </header>
            <main>
              <section class="hero">
                <h2>Key Takeaways</h2>
                <ul>{takeaway_markup}</ul>
              </section>
              <article>
                <h2>Glossary</h2>
                <dl>{glossary_markup}</dl>
              </article>
              <article>
                <h2>Chapters</h2>
                <ul>{chapter_markup}</ul>
              </article>
              <section class="hero">
                <h2>Micro-Lesson Slides</h2>
                {sections_markup}
              </section>
            </main>
            <footer>xAPI-ready output generated by the Shiksha C4GT demo platform.</footer>
          </body>
        </html>
        """
    )
    xapi_events = [
        {"verb": "started", "object": payload.title},
        {"verb": "progressed", "object": payload.title, "progress": 0.5},
        {"verb": "completed", "object": payload.title},
        {"verb": "scored", "object": payload.title, "score": 92},
    ]
    response = LessonBuildResponse(
        title=payload.title,
        status="approved" if payload.approved else "pending_review",
        preview_html=preview_html,
        xapi_events=xapi_events,
        artifacts=[],
    )
    response.artifacts = build_lesson_packages(
        payload.title,
        preview_html,
        payload.branding,
        payload.chapters,
        xapi_events,
    )
    return response
