export const genericEditorSaveFormResponse = {
  id: 'api.form.read',
  params: {
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'save',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'save',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'App Icon',
            name: 'App Icon',
            placeholder: 'App Icon',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the content',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            placeholder: 'Enter Title',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'keywords',
            name: 'Keywords',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
        ],
      },
      created_on: '2019-09-08T03:04:38.104Z',
      last_modified_on: '2020-09-08T12:50:30.070Z',
      rootOrgId: '*',
    },
  },
  ver: '1.0',
};

export const genericEditorReviewFormResponseatree = {
  id: 'api.form.read',
  params: {
    resmsgid: '3f255e2a-c31a-4396-9d95-1e8b42b3ed61',
    msgid: '9754ec68-3862-4489-9f3a-3eca797257e3',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          // {
          //   code: 'appicon',
          //   dataType: 'url',
          //   description: 'App Icon',
          //   editable: true,
          //   index: 1,
          //   inputType: 'file',
          //   label: 'Thumbnail',
          //   name: 'Thumbnail',
          //   placeholder: 'Thumbnail',
          //   renderingHints: {},
          //   required: false,
          //   visible: true,
          // },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of Resource',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title of Resource',
            name: 'Title of Resource',
            placeholder: 'Enter Title',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'Tags',
            name: 'Tags',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'topic',
            visible: true,
            depends: ['subtopic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Topic',
            index: 5,
            label: 'Topic',
            required: true,
            name: 'Topic',
            inputType: 'multiselect',
            placeholder: 'Select Topic',
          },
          {
            code: 'subtopic',
            visible: true,
            depends: [],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Sub Topic',
            index: 6,
            label: 'Sub Topic',
            required: false,
            name: 'Sub Topic',
            inputType: 'multiselect',
            placeholder: 'Sub Topic',
          },
          {
            code: 'author',
            dataType: 'text',
            description: 'Author',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Author',
            name: 'Author',
            placeholder: 'Enter Author name',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'publisher',
            dataType: 'text',
            description: 'Publisher',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'publisher',
            name: 'Pblisher',
            placeholder: 'Enter publisher name',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'resource',
            dataType: 'text',
            description: 'resource',
            editable: true,
            index: 8,
            inputType: 'text',
            label: 'Resource Type',
            name: 'Resource Type',
            placeholder: 'Enter Resource Type',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'language',
            dataType: 'list',
            description: 'Content Language',
            editable: true,
            index: 8,
            inputType: 'select',
            label: 'Content Language',
            name: 'Content Language',
            range: [
              {
                key: 'Hindi',
                name: 'Hindi',
              },
              {
                key: 'English',
                name: 'English',
              },
              {
                key: 'Urdu',
                name: 'Urdu',
              },
              {
                key: 'Sanskrit',
                name: 'Sanskrit',
              },
              {
                key: 'Punjabi',
                name: 'Punjabi',
              },
              {
                key: 'Gujarati',
                name: 'Gujarati',
              },
              {
                key: 'Marathi',
                name: 'Marathi',
              },
              {
                key: 'Tamil',
                name: 'Tamil',
              },
              {
                key: 'Telugu',
                name: 'Telugu',
              },
              {
                key: 'Kannada',
                name: 'Kannada',
              },
              {
                key: 'Malayalam',
                name: 'Malayalam',
              },
              {
                key: 'Odia',
                name: 'Odia',
              },
              {
                key: 'Assamese',
                name: 'Assamese',
              },
              {
                key: 'Bengali',
                name: 'Bengali',
              },
              {
                key: 'Manipuri',
                name: 'Manipuri',
              },
              {
                key: 'Kashmiri',
                name: 'Kashmiri',
              },
            ],
            placeholder: 'Content Language',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'access',
            dataType: 'text',
            description: 'Access',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Access',
            name: 'Access',
            placeholder: 'Enter Access',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'url',
            dataType: 'text',
            description: 'Source Url',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Source Url',
            name: 'Source Url',
            placeholder: 'Enter source url',
            renderingHints: {},
            required: false,
            visible: true,
          },
          // {
          //   code: 'downloadurl',
          //   dataType: 'text',
          //   description: 'Download Url',
          //   editable: true,
          //   index: 2,
          //   inputType: 'text',
          //   label: 'Download Url',
          //   name: 'Download Url',
          //   placeholder: 'Enter download url',
          //   renderingHints: {},
          //   required: false,
          //   visible: true,
          // },
          {
            code: 'posterImage',
            dataType: 'text',
            description: 'Thumbnail',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Thumbnail name',
            name: 'Thumbnail name',
            placeholder: 'Enter Thumbnail name',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'appicon',
            dataType: 'text',
            description: 'App icon',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'AppIcon',
            name: 'AppIcon',
            placeholder: 'Enter AppIcon',
            renderingHints: {},
            required: false,
            visible: true,
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2024-10-10T12:25:59.637Z',
  ver: '1.0',
};

export const genericEditorReviewFormResponsekef = {
  id: 'api.form.read',
  params: {
    resmsgid: 'be3c355f-41cd-4b47-a90a-105e618c4056',
    msgid: '86e6b268-c6b1-4a10-8343-98f312d4a2ae',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'App Icon',
            name: 'App Icon',
            placeholder: 'App Icon',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the content',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            placeholder: 'Enter Title For Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'keywords',
            name: 'Keywords',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'board',
            visible: true,
            depends: ['Medium', 'Grade', 'Subject'],
            editable: true,
            dataType: 'text',
            renderingHints: {},
            description: 'Board',
            index: 7,
            label: 'Board/Syllabus',
            required: true,
            name: 'Board/Syllabus',
            inputType: 'select',
            placeholder: 'Select Board/Syllabus',
          },
          {
            code: 'Medium',
            visible: true,
            depends: ['Grade', 'Subject'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 8,
            label: 'Medium',
            required: true,
            name: 'medium',
            inputType: 'multiselect',
            placeholder: 'Select Medium',
          },
          {
            code: 'Grade',
            visible: true,
            depends: ['Subject'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Class',
            index: 9,
            label: 'Class',
            required: true,
            name: 'Class',
            inputType: 'multiselect',
            placeholder: 'Select Class',
          },
          {
            code: 'Subject',
            visible: true,
            depends: [],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 10,
            label: 'Subject',
            required: true,
            name: 'Subject',
            inputType: 'multiselect',
            placeholder: 'Select Subject',
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-12T07:14:42.275Z',
  ver: '1.0',
};

export const genericEditorReviewFormResponseshiksha = {
  id: 'api.form.read',
  params: {
    resmsgid: '6dfd9647-1355-4708-a3f4-4df1ebed88d2',
    msgid: '7a95e406-0928-483d-b051-d2c962bea578',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'App Icon',
            name: 'App Icon',
            placeholder: 'App Icon',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the content',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            placeholder: 'Enter Title For Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'keywords',
            name: 'Keywords',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'board',
            visible: true,
            depends: ['medium', 'gradeLevel', 'subject', 'topic'],
            editable: true,
            dataType: 'text',
            renderingHints: {},
            description: 'Board',
            index: 7,
            label: 'Board/Syllabus',
            required: true,
            name: 'Board/Syllabus',
            inputType: 'select',
            placeholder: 'Select Board/Syllabus',
          },
          {
            code: 'medium',
            visible: true,
            depends: ['gradeLevel', 'subject', 'topic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 8,
            label: 'Medium',
            required: true,
            name: 'medium',
            inputType: 'multiselect',
            placeholder: 'Select Medium',
          },
          {
            code: 'gradeLevel',
            visible: true,
            depends: ['subject', 'topic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Class',
            index: 9,
            label: 'Class',
            required: true,
            name: 'Class',
            inputType: 'multiselect',
            placeholder: 'Select Class',
          },
          {
            code: 'subject',
            visible: true,
            depends: ['topic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 10,
            label: 'Subject',
            required: true,
            name: 'Subject',
            inputType: 'multiselect',
            placeholder: 'Select Subject',
          },
          {
            code: 'medium',
            dataType: 'list',
            description: 'Language',
            editable: true,
            index: 8,
            inputType: 'select',
            label: 'Language',
            name: 'Langauge',
            placeholder: 'Select Language',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'audience',
            dataType: 'list',
            description: 'Audience',
            editable: true,
            index: 8,
            inputType: 'multiselect',
            label: 'Audience',
            name: 'Audience',
            range: [
              {
                key: 'Student',
                name: 'Student',
              },
              {
                key: 'Teacher',
                name: 'Teacher',
              },
              {
                key: 'Administrator',
                name: 'Administrator',
              },
              {
                key: 'Parent',
                name: 'Parent',
              },
              {
                key: 'Other',
                name: 'Other',
              },
            ],
            placeholder: 'Select Audience',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'attributions',
            dataType: 'list',
            description: 'Attributions',
            editable: true,
            index: 8,
            inputType: 'text',
            label: 'Attributions',
            name: 'attribution',
            placeholder: '',
            renderingHints: {},
            required: false,
            visible: true,
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-20T11:12:58.222Z',
  ver: '1.0',
};

export const genericEditorReviewFormResponsekrdpr = {
  id: 'api.form.read',
  params: {
    resmsgid: '6dfd9647-1355-4708-a3f4-4df1ebed88d2',
    msgid: '7a95e406-0928-483d-b051-d2c962bea578',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'App Icon',
            name: 'App Icon',
            placeholder: 'App Icon',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the content',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            placeholder: 'Enter Title For Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'keywords',
            name: 'Keywords',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'department',
            visible: true,
            depends: [],
            editable: true,
            dataType: 'text',
            renderingHints: {},
            description: 'Department',
            index: 7,
            label: 'Department',
            required: true,
            name: 'Department',
            inputType: 'select',
            placeholder: 'Select Department',
          },
          {
            code: 'categories',
            visible: true,
            depends: [],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 8,
            label: 'Categories',
            required: true,
            name: 'Categories',
            inputType: 'multiselect',
            placeholder: 'Select Categories',
          },
      
          {
            code: 'audience',
            dataType: 'list',
            description: 'Audience',
            editable: true,
            index: 8,
            inputType: 'multiselect',
            label: 'Audience',
            name: 'Audience',
            range: [
              {
                key: 'Student',
                name: 'Student',
              },
              {
                key: 'Teacher',
                name: 'Teacher',
              },
              {
                key: 'Administrator',
                name: 'Administrator',
              },
              {
                key: 'Parent',
                name: 'Parent',
              },
              {
                key: 'Other',
                name: 'Other',
              },
            ],
            placeholder: 'Select Audience',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'attributions',
            dataType: 'list',
            description: 'Attributions',
            editable: true,
            index: 8,
            inputType: 'text',
            label: 'Attributions',
            name: 'attribution',
            placeholder: '',
            renderingHints: {},
            required: false,
            visible: true,
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-20T11:12:58.222Z',
  ver: '1.0',
};
export const genericEditorReviewFormResponsecolab = {
  id: 'api.form.read',
  params: {
    resmsgid: '6dfd9647-1355-4708-a3f4-4df1ebed88d2',
    msgid: '7a95e406-0928-483d-b051-d2c962bea578',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'App Icon',
            name: 'App Icon',
            placeholder: 'App Icon',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the content',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            placeholder: 'Enter Title For Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'keywords',
            name: 'Keywords',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'board',
            visible: true,
            depends: ['medium', 'gradeLevel', 'subject', 'topic'],
            editable: true,
            dataType: 'text',
            renderingHints: {},
            description: 'Board',
            index: 7,
            label: 'Board/Syllabus',
            required: true,
            name: 'Board/Syllabus',
            inputType: 'select',
            placeholder: 'Select Board/Syllabus',
          },
          {
            code: 'medium',
            visible: true,
            depends: ['gradeLevel', 'subject', 'topic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 8,
            label: 'Medium',
            required: true,
            name: 'medium',
            inputType: 'multiselect',
            placeholder: 'Select Medium',
          },
          {
            code: 'gradeLevel',
            visible: true,
            depends: ['subject', 'topic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Class',
            index: 9,
            label: 'Class',
            required: true,
            name: 'Class',
            inputType: 'multiselect',
            placeholder: 'Select Class',
          },
          {
            code: 'subject',
            visible: true,
            depends: ['topic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 10,
            label: 'Subject',
            required: true,
            name: 'Subject',
            inputType: 'multiselect',
            placeholder: 'Select Subject',
          },
          {
            code: 'medium',
            dataType: 'list',
            description: 'Language',
            editable: true,
            index: 8,
            inputType: 'select',
            label: 'Language',
            name: 'Langauge',
            placeholder: 'Select Language',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'audience',
            dataType: 'list',
            description: 'Audience',
            editable: true,
            index: 8,
            inputType: 'multiselect',
            label: 'Audience',
            name: 'Audience',
            range: [
              {
                key: 'Student',
                name: 'Student',
              },
              {
                key: 'Teacher',
                name: 'Teacher',
              },
              {
                key: 'Administrator',
                name: 'Administrator',
              },
              {
                key: 'Parent',
                name: 'Parent',
              },
              {
                key: 'Other',
                name: 'Other',
              },
            ],
            placeholder: 'Select Audience',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'url',
            dataType: 'text',
            description: 'url',
            editable: true,
            index: 8,
            inputType: 'text',
            label: 'Url',
            name: 'url',
            placeholder: '',
            renderingHints: {},
            required: false,
            visible: true,
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-20T11:12:58.222Z',
  ver: '1.0',
};
export const genericEditorReviewFormResponseswadhaar = {
  id: 'api.form.read',
  params: {
    resmsgid: '3f255e2a-c31a-4396-9d95-1e8b42b3ed61',
    msgid: '9754ec68-3862-4489-9f3a-3eca797257e3',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'Thumbnail',
            name: 'Thumbnail',
            placeholder: 'Thumbnail',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of Resource',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title of Resource',
            name: 'Title of Resource',
            placeholder: 'Enter Title',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'Tags',
            name: 'Tags',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'topic',
            visible: true,
            depends: ['subTopic'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Topic',
            index: 5,
            label: 'Topic',
            required: true,
            name: 'Topic',
            inputType: 'multiselect',
            placeholder: 'Select Topic',
          },
          {
            code: 'subTopic',
            visible: true,
            depends: [],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Sub Topic',
            index: 6,
            label: 'Sub Topic',
            required: false,
            name: 'Sub Topic',
            inputType: 'multiselect',
            placeholder: 'Sub Topic',
          },
          {
            code: 'author',
            dataType: 'text',
            description: 'Author',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Author',
            name: 'Author',
            placeholder: 'Enter Author name',
            renderingHints: {},
            required: false,
            visible: true,
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2024-10-10T12:25:59.637Z',
  ver: '1.0',
};

export const genericEditorReviewFormResponse = {
  id: 'api.form.read',
  params: {
    resmsgid: 'be3c355f-41cd-4b47-a90a-105e618c4056',
    msgid: '86e6b268-c6b1-4a10-8343-98f312d4a2ae',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'App Icon',
            name: 'App Icon',
            placeholder: 'App Icon',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the content',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            placeholder: 'Enter Title For Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'keywords',
            name: 'Keywords',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'board',
            visible: true,
            depends: ['Medium', 'Grade', 'Subject'],
            editable: true,
            dataType: 'text',
            renderingHints: {},
            description: 'Board',
            index: 7,
            label: 'Board/Syllabus',
            required: true,
            name: 'Board/Syllabus',
            inputType: 'select',
            placeholder: 'Select Board/Syllabus',
          },
          {
            code: 'Medium',
            visible: true,
            depends: ['Grade', 'Subject'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 8,
            label: 'Medium',
            required: true,
            name: 'medium',
            inputType: 'multiselect',
            placeholder: 'Select Medium',
          },
          {
            code: 'Grade',
            visible: true,
            depends: ['Subject'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Class',
            index: 9,
            label: 'Class',
            required: true,
            name: 'Class',
            inputType: 'multiselect',
            placeholder: 'Select Class',
          },
          {
            code: 'Subject',
            visible: true,
            depends: [],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 10,
            label: 'Subject',
            required: true,
            name: 'Subject',
            inputType: 'multiselect',
            placeholder: 'Select Subject',
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-12T07:14:42.275Z',
  ver: '1.0',
};

export const contentEditorQuestionFormResponse = {
  id: 'api.form.read',
  params: {
    resmsgid: '8437ee1d-b708-4f3f-9ec9-31d9a203a3c6',
    msgid: 'dd4e9440-9257-4c49-a668-7b79a6e6f83c',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'questions',
      action: 'question-filter-view',
      component: '*',
      framework: '*',
      data: {
        action: 'question-filter-view',
        templateName: 'filterMetaDataTemplate',
        fields: [
          {
            code: 'searchText',
            dataType: 'text',
            description: ' by question title',
            editable: true,
            inputType: 'text',
            label: 'Search',
            name: 'Search',
            index: 0,
            placeholder: 'Search by question title',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'level',
            dataType: 'text',
            description: 'Add Notes',
            editable: true,
            index: 2,
            inputType: 'select',
            label: 'Difficulty',
            name: 'level',
            placeholder: 'Select Level',
            range: ['EASY', 'MEDIUM', 'DIFFICULT'],
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'questionType',
            dataType: 'list',
            description: 'Class',
            editable: true,
            index: 3,
            inputType: 'multiselect',
            label: 'Question Type',
            name: 'Question Type',
            placeholder: 'Question Type',
            range: [
              'Multiple Choice Questions',
              'Fill in the Blanks',
              'Match the Following',
            ],
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'myQuestions',
            dataType: 'toggle',
            description: 'My Questions',
            editable: true,
            inputType: 'checkbox',
            label: 'My Questions',
            name: 'My Questions',
            placeholder: 'My Questions',
            renderingHints: {},
            required: false,
            visible: true,
            index: 9,
          },
        ],
      },
      created_on: '2019-09-08T15:10:47.019Z',
      last_modified_on: '2020-08-16T11:48:08.835Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-20T04:27:33.588Z',
  ver: '1.0',
};

export const contentEditorQuestionMetaFormResponse = {
  id: 'api.form.read',
  params: {
    resmsgid: '1d4dc61c-e66b-41ba-aed2-00509bd4c9b7',
    msgid: '7f7f8182-5461-488d-93cc-3f6fdf11feaf',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'questions',
      action: 'question-meta-save',
      component: '*',
      framework: '*',
      data: {
        action: 'question-meta-save',
        templateName: 'questionMetaDataTemplate',
        fields: [
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the question',
            editable: true,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            index: 0,
            placeholder: 'Enter the Title',
            renderingHints: {},
            required: true,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Enter the Description',
            renderingHints: {},
            required: false,
            visible: true,
            index: 1,
          },
          {
            code: 'medium',
            dataType: 'text',
            description: 'Language',
            editable: true,
            index: 8,
            inputType: 'select',
            label: 'Language',
            name: 'Language',
            placeholder: 'Select Language',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'qlevel',
            dataType: 'text',
            description: 'Add Notes',
            editable: true,
            index: 3,
            inputType: 'select',
            label: 'Level',
            name: 'qlevel',
            placeholder: 'Select Level',
            range: ['EASY', 'MEDIUM', 'DIFFICULT'],
            renderingHints: {},
            required: true,
            visible: true,
          },
          {
            code: 'max_score',
            dataType: 'number',
            description: '',
            editable: true,
            index: 4,
            inputType: 'number',
            label: 'Max Score',
            name: 'max_score',
            placeholder: 'Enter the Max Score',
            renderingHints: {},
            required: true,
            visible: true,
            validation: [
              {
                type: 'min',
                value: '1',
                message: '',
              },
            ],
          },
        ],
      },
      created_on: '2020-08-19T11:42:18.732Z',
      last_modified_on: '2020-08-16T11:48:17.934Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-20T05:54:42.223Z',
  ver: '1.0',
};

export const genericEditorRequestForChangesFormResponse = {
  id: 'api.form.read',
  params: {
    resmsgid: 'fb345240-8d49-459d-a99c-4fcf3aa04da2',
    msgid: 'b54b2ac7-2db4-406a-80f7-140d86bcccbb',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'requestforchanges',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'requestforchanges',
        fields: [
          {
            title:
              'Please confirm that ALL the following items are verified (by ticking the check-boxes) before you can publish:',
            contents: [
              {
                name: 'Usability',
                checkList: [
                  'Correct Spellings and Grammar',
                  'Simple Language',
                  'Content/Audio/Video quality',
                  'Suitable font size for app and portal',
                  'Copyright infringement (images and texts)',
                ],
              },
              {
                name: 'Content details',
                checkList: [
                  'Appropriate Title',
                  'Standard description of the course/resource',
                  'Relevant tags and keywords',
                  'Appropritae image ',
                ],
              },
            ],
          },
        ],
      },
      created_on: '2019-09-08T15:25:00.291Z',
      last_modified_on: '2020-08-24T06:06:08.120Z',
      rootOrgId: '*',
    },
  },
  ts: '2024-12-12T14:40:25.246Z',
  ver: '1.0',
};

export const telemetryResponse = {
  id: 'api.telemetry.post',
  params: {
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    message: 'This is mocked response',
  },
  ver: '1.0',
};

export const creatLockResponse = {
  id: 'api.lock.create',
  params: {
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    lockKey: '69d82e1c-6d91-4b2e-a873-39ebeab007b9',
    expiresAt: '2026-10-09T12:53:41.138Z',
    expiresIn: 63072000,
  },
};
export const genericEditorReviewFormResponsebadal = {
  id: 'api.form.read',
  params: {
    resmsgid: '6dfd9647-1355-4708-a3f4-4df1ebed88d2',
    msgid: '7a95e406-0928-483d-b051-d2c962bea578',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'review',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'review',
        fields: [
          {
            code: 'appicon',
            dataType: 'url',
            description: 'App Icon',
            editable: true,
            index: 1,
            inputType: 'file',
            label: 'App Icon',
            name: 'App Icon',
            placeholder: 'App Icon',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'name',
            dataType: 'text',
            description: 'Title of the content',
            editable: true,
            index: 2,
            inputType: 'text',
            label: 'Title',
            name: 'Title',
            placeholder: 'Enter Title For Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'description',
            dataType: 'text',
            description: 'Brief description',
            editable: true,
            index: 3,
            inputType: 'textarea',
            label: 'Description',
            name: 'Description',
            placeholder: 'Brief description about the Book',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'keywords',
            dataType: 'list',
            description: 'Keywords for the content',
            editable: true,
            index: 4,
            inputType: 'keywordsuggestion',
            label: 'keywords',
            name: 'Keywords',
            placeholder: 'Enter Keywords',
            required: false,
            visible: true,
          },
          {
            code: 'climatetopic',
            visible: true,
            depends: [
              'environmentaltheme',
              'climateaction',
              'geographicalphenomenon',
            ],
            editable: true,
            dataType: 'text',
            renderingHints: {},
            description: 'Board',
            index: 7,
            label: 'Climate Topic',
            required: true,
            name: 'Climate Topic',
            inputType: 'select',
            placeholder: 'Select Climate Topic',
          },
          {
            code: 'environmentaltheme',
            visible: true,
            depends: ['climateaction', 'geographicalphenomenon'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 8,
            label: 'Environmental Theme',
            required: true,
            name: 'Environmental Theme',
            inputType: 'multiselect',
            placeholder: 'Select Environmental Theme',
          },
          {
            code: 'climateaction',
            visible: true,
            depends: ['geographicalphenomenon'],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: 'Climate Action',
            index: 9,
            label: 'Climate Action',
            required: true,
            name: 'Climate Action',
            inputType: 'multiselect',
            placeholder: 'Select Climate Action',
          },
          {
            code: 'geographicalphenomenon',
            visible: true,
            depends: [],
            editable: true,
            dataType: 'list',
            renderingHints: {},
            description: '',
            index: 10,
            label: 'Geographical Phenomenon',
            required: true,
            name: 'Geographical Phenomenon',
            inputType: 'multiselect',
            placeholder: 'Select Geographical Phenomenon',
          },
          {
            code: 'medium',
            dataType: 'list',
            description: 'Language',
            editable: true,
            index: 8,
            inputType: 'select',
            label: 'Language',
            name: 'Langauge',
            placeholder: 'Select Language',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'audience',
            dataType: 'list',
            description: 'Audience',
            editable: true,
            index: 8,
            inputType: 'multiselect',
            label: 'Audience',
            name: 'Audience',
            range: [
              {
                key: 'Student',
                name: 'Student',
              },
              {
                key: 'Teacher',
                name: 'Teacher',
              },
              {
                key: 'Administrator',
                name: 'Administrator',
              },
              {
                key: 'Parent',
                name: 'Parent',
              },
              {
                key: 'Other',
                name: 'Other',
              },
            ],
            placeholder: 'Select Audience',
            renderingHints: {},
            required: false,
            visible: true,
          },
          {
            code: 'attributions',
            dataType: 'list',
            description: 'Attributions',
            editable: true,
            index: 8,
            inputType: 'text',
            label: 'Attributions',
            name: 'attribution',
            placeholder: '',
            renderingHints: {},
            required: false,
            visible: true,
          },
        ],
      },
      created_on: '2024-07-31T06:21:34.669Z',
      last_modified_on: '2024-07-31T07:20:14.642Z',
      rootOrgId: '*',
    },
  },
  ts: '2025-03-20T11:12:58.222Z',
  ver: '1.0',
};

export const publishResourceFormResponse = {
  id: 'api.form.read',
  params: {
    resmsgid: '0455438d-8bd5-4bfb-a97c-0d962cab1951',
    msgid: '2db53598-185f-44f9-a35c-e760e08fe62a',
    status: 'successful',
  },
  responseCode: 'OK',
  result: {
    form: {
      type: 'content',
      subtype: 'resource',
      action: 'publish',
      component: '*',
      framework: '*',
      data: {
        templateName: 'defaultTemplate',
        action: 'publish',
        fields: [
          {
            title:
              'Please confirm that ALL the following items are verified (by ticking the check-boxes) before you can publish:',
            contents: [
              {
                name: 'Usability',
                checkList: [
                  'Correct Spellings and Grammar',
                  'Simple Language',
                  'Content/Audio/Video quality',
                  'Suitable font size for app and portal',
                  'Copyright infringement (images and texts)',
                ],
              },
              {
                name: 'Content details',
                checkList: [
                  'Appropriate Title',
                  'Standard description of the course/resource',
                  'Relevant tags and keywords',
                  'Appropritae image ',
                ],
              },
            ],
          },
        ],
      },
      created_on: '2019-09-08T15:25:39.638Z',
      last_modified_on: '2020-08-16T11:47:24.215Z',
      rootOrgId: '*',
    },
  },
  ts: '2024-12-24T05:46:18.384Z',
  ver: '1.0',
};
